StatusBar colouring, tag support, and oUF checking
Rainrider/oUF_ArtifactPower pull request #1
Opened 2017-08-29 21:16 UTC by sBaildon

Small PR to:

* Add support for colouring the widget
* Tag support
* Don't waste time loading if oUF isn't installed

Doesn't remove any features, will stay compatible with current installs.

2017-08-30 21:59 UTC, Rainrider requested changes
Thank you for the PR! Could you please resolve the requested changes, I'll merge then. Basically just leave it to the tags and remove the rest

2017-08-30 21:59 UTC, Rainrider commented on oUF_ArtifactPower.lua
> +
I'm against that as it is very limiting. Some refactoring in the lines above it solve the lack of options for coloring. I'll fix this myself, thanks for pointing out the use case.

2017-08-30 21:59 UTC, Rainrider commented on oUF_ArtifactPower.lua
This is not needed. oUF is a required dependency (see the .toc)

2017-09-01 11:44 UTC, sBaildon commented
Rebased to to remove the changes you're not interested in, and to squash the various tag support commits.

What's the plan for supporting colour? I figured that people would be expected to call `SetStatusBarColor` themselves when they initialise the `StatusBar`

2017-09-01 14:34 UTC, Rainrider commented
Yes, that is the plan, I'll just factor the color check in its own if block. I'll review the rebase when I'm home later, thank you again

2017-09-01 22:45 UTC, merged